#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Configure system package mirror (Alpine/APK or Ubuntu/apt)
if [[ -n "${PACKAGES_MIRROR}" ]]; then
    if [[ -f /sbin/apk ]]; then
        echo "[pkg-install-init] **** Configuring system package mirror: ${PACKAGES_MIRROR} ****"
        sed -i "s|dl-cdn.alpinelinux.org|${PACKAGES_MIRROR}|g" /etc/apk/repositories
    elif [[ -f /usr/bin/apt ]]; then
        echo "[pkg-install-init] **** Configuring system package mirror: ${PACKAGES_MIRROR} ****"
        shopt -s nullglob
        sed -i \
            -e "s|archive.ubuntu.com|${PACKAGES_MIRROR}|g" \
            -e "s|security.ubuntu.com|${PACKAGES_MIRROR}|g" \
            -e "s|ports.ubuntu.com|${PACKAGES_MIRROR}|g" \
            /etc/apt/sources.list \
            /etc/apt/sources.list.d/* \
            /etc/apt/sources.d/*
        shopt -u nullglob
    fi
fi

# Configure pip mirror
if [[ -n "${PIP_MIRROR}" ]]; then
    echo "[pkg-install-init] **** Configuring pip mirror: ${PIP_MIRROR} ****"
    mkdir -p /root/.config/pip
    echo -e "[global]\nindex-url = ${PIP_MIRROR}" > /root/.config/pip/pip.conf
fi

# Exit if no installable packages are provided
if [[ -z "${INSTALL_PACKAGES+x}" ]] && [[ -z "${INSTALL_PIP_PACKAGES+x}" ]]; then
    echo "[pkg-install-init] **** No packages to install ****"
    exit 0
fi

if [[ -n "${INSTALL_PIP_PACKAGES}" ]] && [[ -f /usr/bin/apt ]]; then
    echo "\
        python3-dev \
        python3-pip" >> /mod-repo-packages-to-install.list
elif [[ -n "${INSTALL_PIP_PACKAGES}" ]] && [[ -f /sbin/apk ]]; then
    echo "\
        python3-dev \
        py3-pip" >> /mod-repo-packages-to-install.list
fi

# Split list of packages on delimiter '|'
IFS="|" read -r -a SPLIT_INSTALL_PACKAGES <<< "${INSTALL_PACKAGES}"
for PKG in "${SPLIT_INSTALL_PACKAGES[@]}"; do
    echo "[pkg-install-init] **** Adding ${PKG} to OS package install list ****"
    echo "${PKG}" >> /mod-repo-packages-to-install.list
done

IFS="|" read -r -a SPLIT_INSTALL_PIP_PACKAGES <<< "${INSTALL_PIP_PACKAGES}"
for PKG in "${SPLIT_INSTALL_PIP_PACKAGES[@]}"; do
    echo "[pkg-install-init] **** Adding ${PKG} to pip install list ****"
    echo "${PKG}" >> /mod-pip-packages-to-install.list
done
